### ISSUE TITLE
Contribution guidelines

### ISSUE THREAD

**Issue by beve** [LottieFiles/lottie-js#22]
Hello lottie-js team, and thank you for your work on this awesome package.

We use lottie-js in our own product [jitter.video](https://jitter.video/) to generate Lottie files. To support our use case we opened #19  and #21. We also would like to improve the release process in the future, using Earthly to be able to run the pipeline locally and leveraging GitHub releases.

Did we respect your contribution guidelines? Do you think our patches are fit for lottie-js?

We would like to avoid a fork as much as possible, but we understand lottie-js was meant to be a parser, so please don't hesitate to tell us if you think our contributions don't fit the scope of the project.

Regards,

Christophe

**Comment by karamalie** [comment]
Hi @beve ,
I ll go through the PRs and get back to you. 

The project is most definitely a work in progress and is the foundation for new tools we work on and as such, we work on it actively too. Contributions are appreciated but there are internal fixes ongoing so i'll make sure they don't clash or cause breaking changes unless necessary.

In case you 've not come across this write-up, do have a look so as to why we started the project https://karamalie.medium.com/the-lottie-json-object-402b6b8fb600
and the docs are here https://docs.lottiefiles.com/lottie-js/

**Comment by karamalie** [comment]
Merged PR in.
